base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

recovery_behavior_enabled: false
clearing_rotation_allowed: false
controller_frequency: 30.0
planner_patiience: 15.0
controller_patiience: 15.0
planner_frequency: 2.0
shutdown_costmaps: false 
oscillation_timeout: 0.0
oscillation_distance: 0.5
