base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

recovery_behavior_enabled: true
clearing_rotation_allowed: true
controller_frequency: 10.0
planner_patiience: 5.0
controller_patiience: 3.0
planner_frequency: 2.0
shutdown_costmaps: true
oscillation_timeout: 0.0
oscillation_distance: 0.2
