TrajectoryPlannerROS:
    acc_lim_theta: 3.2 #1.6 #3.2
    acc_lim_x: 2.5 #1.0 
    acc_lim_y: 2.5 #0.0
    max_vel_theta: 0.5 # 1.5
    max_vel_x: 0.55 
    min_vel_x: 0.0
    max_rotational_vel: 1.0 #0.5
    min_in_place_rotational_vel: 0.4


    xy_goal_tolerance: 0.30 #0.1 # 0.15
    yaw_goal_tolerance: 0.15 #0.05 #0.1
    latch_xy_goal_tolerance: true

    holonomic_robot: false

    sim_time: 1.5 #1.7 #4.0
    vx_samples: 6 #3 #10
    vtheta_samples: 30 #20

    meter_scoring: true

    # dwa: true #false
    #pdist_scale: 0.6
    # gdist_scale: 0.8
    path_distance_bias: 0.6
    goal_distance_bias: 0.8
    occdist_scale: 0.01 #0.05

    controller_frequency: 10.0
    controller_patience: 3.0
    oscillation_timeout: 5.0
    max_planning_retries: 100

    meter_scoring: true
