# local costmap params 

local_costmap:
        plugins:
                - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
                - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

                # 各TFフレームの設定
        global_frame: tf_demo_map
        robot_base_frame: base_link 
                  #footprint: [[],[],[],[]]
                  #自分の周りの一部だけcostmapを使うオプション 
                  #static_map: false
        rolling_window: true

                  # ローカルコストマップの計算範囲
        width: 6.0
        height: 6.0
                  # ローカルコストマップの解像度
        resolution: 0.05
                  # タイムスタンプのずれの許容量
        transform_tolerance: 0.5
                  # 更新頻度の設定
        update_frequency: 2.0
        publish_frequency: 2.0

                  #Laserscan, PointCloud, PointCloud2の型から複数データ受け取れる.    
        obstacle_layer: 
                  observation_sources: laser_scan_sensor
                  laser_scan_sensor:
                          sensor_frame: base_link
                          topic: /scan_multi
                          data_type: LaserScan
                          #データをmapを埋める、クリアするのに使うか指定両trueでOK
                          marking: true
                          clearing: true
                          #インデントはいいのか
        inflation_layer:
                          #指定の距離だけコストマップが膨張
                inflation_radius: 0.9 


