#costmap common params for MEGAROVER

robot_radius: 0.5

obstacle_layer:
        enabled: true



        # これ以下の距離にある物体を障害物として扱う
        obstacle_range: 3.5
        # これ以下の距離に物体が検出された場合、ロボットとその物体との間に障害物はないものとして扱う
        raytrace_range: 5.0

# ロボットの大きさに関するパラメータ
#footprint: [[1.0, -0.5], [-0.5, 0.5], [-0.3, -0.3], [0.3, -0.3]]
#inflation_radius: 0.2

# コストマップのタイプの設定
#map_type: costmap_2d

        # LRFの設定 
        observation_sources: laser_scan_sensor 
        laser_scan_sensor: {sensor_frame: tim_link, data_type: LaserScan, topic: scan_multi , marking: true, clearing: true}

inflation_layer:
        enabled: true
        inflation_radius: 0.2
