global_costmap:
        footprint: [[1.0, -0.5], [-0.5, 0.5], [-0.3, -0.3], [0.3, -0.3]]
        inflation_radius: 0.55
        update_frequency: 2.0
        static_map: true
        global_frame: odom
        robot_base_frame: base_link
