obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[0.90, -0.35], [-0.30, -0.40], [-0.30, 0.40],[0.90, 0.35]]
inflation_radius: 0.1
#transform_tolerance: 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: tim_scan, marking: true, clearing: true}

