recovery_behavior_enabled: false
clearing_rotation_allowed: false
controller_frequency: 60.0
planner_patiience: 60.0
controller_patiience: 15.0
planner_frequency: 0.0
shutdown_costmaps: false 
oscillation_timeout: 0.0
oscillation_distance: 0.5
