navsat_transform:
  frequency: 30
  delay: 3.0
  magnetic_declination_radians: 0 # For lat/long 55.944831, -3.186998
  yaw_offset: 0  # IMU reads 0 facing magnetic north, not east
  zero_altitude: true 
  broadcast_cartesian_transform: false
  publish_filtered_gps: true
  use_odometry_yaw: true 
  wait_for_datum: false

